name: Build and Deploy React App with Docker

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker
      run: |
        sudo apt-get install docker.io
        sudo systemctl start docker
        sudo systemctl enable docker

    - name: Build Docker image
      run: |
        docker build -t my-react-app .

    - name: Push Docker image to Docker Hub
      run: |
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker tag my-react-app your-username/my-react-app:latest
        docker push your-username/my-react-app:latest

    # Optional: Deploy to AWS ECS or any containerized service after building the Docker image
